FROM tensorflow/tensorflow:1.15.0-gpu-py3

COPY requirements.txt /tmp

WORKDIR /tmp

RUN pip --no-cache-dir install -r requirements.txt

RUN apt-get -y update && apt-get install -qyy \
   -o APT::Install-Recommends=false -o APT::Install-Suggests=false \
   xfoil

COPY xserver.config /tmp


ENV DEBIAN_FRONTEND noninteractive
ENV DISPLAY :0

RUN apt-get install -y xorg
RUN apt-get install -y xserver-xorg-video-dummy x11-apps
