#!/bin/bash

cd /home/mpib/brinkmann/repros/airfoil-opt-gan

echo $SLURM_JOB_NAME
echo $SLURM_JOB_ID

singularity exec --nv /home/mpib/brinkmann/docker/images/mctest_tf1.sif python train.py $SLURM_JOB_NAME &> /home/mpib/brinkmann/data/logs/${SLURM_JOB_NAME}_${SLURM_JOB_ID}.log

